#!/usr/bin/perl
# gen-uninames.pl: writes library/ccl_uninames.pl, THE UNICODE NAME TABLE for `\N{NAME}' (0.103), from Perl's
# Unicode::UCD -- the Name property of every assigned character (the families named by their code point's hex
# digits as runs, `ccl_uname_range(Prefix, Lo, Hi)', which both lexers compute), then the NAME ALIASES of the
# kinds clang accepts (control, correction, alternate, figment; never an abbreviation) as facts of the same shape.
#     perl module/gen-uninames.pl > library/ccl_uninames.pl
# module/build.sh spells the same facts into module/ccl_uninames.h for the native lexer, so the table is written once.
use strict; use warnings;
use Unicode::UCD qw(prop_invmap);
my $ver = Unicode::UCD::UnicodeVersion();
# a Hangul syllable's name is algorithmic (Unicode 3.12): the leading, vowel and trailing Jamo's short names
my @JL = ('G', 'GG', 'N', 'D', 'DD', 'R', 'M', 'B', 'BB', 'S', 'SS', '', 'J', 'JJ', 'C', 'K', 'T', 'P', 'H');
my @JV = qw(A AE YA YAE EO E YEO YE O WA WAE OE YO U WEO WE WI YU EU YI I);
my @JT = ('', qw(G GG GS N NJ NH D L LG LM LB LS LT LP LH M B BS S SS NG J C K T P H));
sub hangul_name { my $s = $_[0] - 0xAC00; my $t = $s % 28; my $v = int($s / 28) % 21; my $l = int($s / 588);
    return "HANGUL SYLLABLE " . $JL[$l] . $JV[$v] . $JT[$t] }
my ($l, $m) = prop_invmap("Name");
my (@names, @fam);
for my $i (0 .. $#$l - 1) {
    my ($lo, $hi, $v) = ($$l[$i], $$l[$i + 1] - 1, $$m[$i]);
    next if $v eq '';
    if ($v =~ /^(.*-)<code point>$/) { push @fam, [$1, $lo, $hi]; next }
    if ($v =~ /<hangul syllable>/) { push @names, [hangul_name($_), $_] for $lo .. $hi; next }
    die "unexpected map '$v' for $lo..$hi" if $v =~ /</ or $hi != $lo;
    push @names, [$v, $lo];
}
my ($al, $am) = prop_invmap("Name_Alias");
my @aliases;
for my $i (0 .. $#$al - 1) {
    my $v = $$am[$i]; next if $v eq '';
    for my $e (ref $v ? @$v : ($v)) {
        my ($n, $t) = $e =~ /^(.*): (\w+)$/ or die "alias '$e'";
        push @aliases, [$n, $$al[$i], $t] if $t =~ /^(control|correction|alternate|figment)$/;
    }
}
my $nn = @names; my $na = @aliases; my $nf = @fam;
print <<"HEAD";
%% ccl_uninames.pl -- THE UNICODE NAME TABLE for `\\N{NAME}' (C++23 [lex.charset], C23 6.4.3; 0.103): one fact per
%% assigned character, `ccl_uname(Name, CodePoint)', the Name property of Unicode $ver as Perl's Unicode::UCD gives
%% it ($nn facts, the Hangul syllables among them) -- GENERATED by module/gen-uninames.pl, never edited by hand. The
%% families whose names are their code point's hex digits (CJK UNIFIED IDEOGRAPH-4E00 and kin) are $nf runs at the end,
%% `ccl_uname_range(Prefix, Lo, Hi)', computed by both lexers and not listed. After the names, the $na NAME ALIASES of
%% the kinds clang accepts (control, correction, alternate, figment; an abbreviation such as `NUL' or `LF' it refuses,
%% and so does this reader), facts of the same shape. The DCG loads this file on the first `\\N{' it meets
%% (ccl_uname_value in ccl_syntax); module/build.sh spells the same facts into module/ccl_uninames.h for the native
%% lexer, so the table is written once.
HEAD
printf "ccl_uname('%s', %d).\n", @$_ for @names;
print "%% THE NAME ALIASES (control, correction, alternate, figment), each resolving as a name does\n";
printf "ccl_uname('%s', %d).   %% %s\n", @$_ for @aliases;
print "%% THE FAMILIES NAMED BY THEIR CODE POINT'S HEX DIGITS, one fact per run: `ccl_uname_range(Prefix, Lo, Hi)'\n";
printf "ccl_uname_range('%s', %d, %d).\n", @$_ for @fam;
